In [ ]:
import pandas as pd

from orion.data import load_signal
from mlblocks import MLPipeline

pipeline_name = 'lstm_dynamic_threshold'

pipeline = MLPipeline(pipeline_name)
hyperparameters = {
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

pipeline.set_hyperparameters(hyperparameters)
#pipeline.primitives


SIGNALS = [
    'P-1', 'S-1', 'E-1', 'E-2', 'E-3', 'E-4', 'E-5', 'E-6', 'E-7',
    'E-8', 'E-9', 'E-10', 'E-11', 'E-12', 'E-13', 'A-1', 'D-1', 'P-3',
    'D-2', 'D-3', 'D-4', 'A-2', 'A-3', 'A-4', 'G-1', 'G-2', 'D-5',
    'D-6', 'D-7', 'F-1', 'P-4', 'G-3', 'T-1', 'T-2', 'D-8', 'D-9',
    'F-2', 'G-4', 'T-3', 'D-11',  'B-1', 'G-6', 'G-7', 'P-7',
    'R-1', 'A-5', 'A-6', 'A-7', 'D-13', 'A-8', 'A-9', 'F-3', 'M-6',
    'M-1', 'M-2', 'S-2', 'P-10', 'T-4', 'T-5', 'F-7', 'M-3', 'M-4',
    'M-5', 'P-15', 'C-1', 'C-2', 'T-12', 'T-13', 'F-4', 'F-5', 'D-14',
    'T-9', 'P-14', 'T-8', 'P-11', 'D-15', 'D-16', 'M-7', 'F-8'
]
SMAP=[  'P-1', 'S-1', 'E-1', 'E-2', 'E-3', 'E-4', 'E-5', 'E-6', 'E-7',
    'E-8', 'E-9', 'E-10', 'E-11', 'E-12', 'E-13', 'A-1', 'D-1', 'P-3',
    'D-2', 'D-3', 'D-4', 'A-2', 'A-3', 'A-4', 'G-1', 'G-2', 'D-5',
    'D-6', 'D-7', 'F-1', 'P-4', 'G-3', 'T-1', 'T-2', 'D-8', 'D-9',
    'F-2', 'G-4', 'T-3', 'D-11', 'B-1', 'G-6', 'G-7', 'P-7',
    'R-1', 'A-5', 'A-6', 'A-7', 'D-13', 'A-8', 'A-9', 'F-3']


MSL=['M-6',
    'M-1', 'M-2', 'S-2', 'P-10', 'T-4', 'T-5', 'F-7', 'M-3', 'M-4',
    'M-5', 'P-15', 'C-1', 'C-2', 'T-12', 'T-13', 'F-4', 'F-5', 'D-14',
    'T-9', 'P-14', 'T-8', 'P-11', 'D-15', 'D-16', 'M-7', 'F-8']

error=[]
for signal_name in SMAP:
    data = load_signal(signal_name)
    context = pipeline.fit(data, output_=0)
    context = pipeline.fit(**context, output_=1, start_=1)
    context = pipeline.fit(**context, output_=2, start_=2)
    context = pipeline.fit(**context, output_=3, start_=3)
    context = pipeline.fit(**context, output_=4, start_=4)
    context = pipeline.fit(**context, output_=5, start_=5)
    print(context['errors'])
    error.append(context['errors'])
    


Train on 8901 samples, validate on 2226 samples
Epoch 1/5
8901/8901 [==============================] - 45s 5ms/step - loss: 0.0986 - mse: 0.0986 - val_loss: 0.0565 - val_mse: 0.0565
Epoch 2/5
8901/8901 [==============================] - 41s 5ms/step - loss: 0.0507 - mse: 0.0507 - val_loss: 0.0419 - val_mse: 0.0419
Epoch 3/5
8901/8901 [==============================] - 41s 5ms/step - loss: 0.0440 - mse: 0.0440 - val_loss: 0.0406 - val_mse: 0.0406
Epoch 4/5
8901/8901 [==============================] - 42s 5ms/step - loss: 0.0418 - mse: 0.0418 - val_loss: 0.0405 - val_mse: 0.0405
Epoch 5/5
11127/11127 [==============================] - 20s 2ms/step
[0.04567837 0.10763891 0.16152453 ... 0.13220571 0.13116394 0.13359987]
Train on 7919 samples, validate on 1980 samples
Epoch 1/5
7919/7919 [==============================] - 41s 5ms/step - loss: 0.1955 - mse: 0.1955 - val_loss: 0.3266 - val_mse: 0.3266
Epoch 2/5
7919/7919 [==============================] - 37s 5ms/step - loss: 0.1927 - mse: 0.

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



11237/11237 [==============================] - 23s 2ms/step
[0.02046771 0.02075878 0.0177553  ... 0.05458219 0.0570202  0.0562772 ]
Train on 7946 samples, validate on 1987 samples
Epoch 1/5
4672/7946 [================>.............] - ETA: 16s - loss: 0.0454 - mse: 0.0454

In [1]:
!pip install orion-ml

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import pandas as pd

from orion.data import load_signal
from mlblocks import MLPipeline

pipeline_name = 'lstm_dynamic_threshold'

pipeline = MLPipeline(pipeline_name)
hyperparameters = {
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

pipeline.set_hyperparameters(hyperparameters)
#pipeline.primitives


SIGNALS = [
    'P-1', 'S-1', 'E-1', 'E-2', 'E-3', 'E-4', 'E-5', 'E-6', 'E-7',
    'E-8', 'E-9', 'E-10', 'E-11', 'E-12', 'E-13', 'A-1', 'D-1', 'P-3',
    'D-2', 'D-3', 'D-4', 'A-2', 'A-3', 'A-4', 'G-1', 'G-2', 'D-5',
    'D-6', 'D-7', 'F-1', 'P-4', 'G-3', 'T-1', 'T-2', 'D-8', 'D-9',
    'F-2', 'G-4', 'T-3', 'D-11',  'B-1', 'G-6', 'G-7', 'P-7',
    'R-1', 'A-5', 'A-6', 'A-7', 'D-13', 'A-8', 'A-9', 'F-3', 'M-6',
    'M-1', 'M-2', 'S-2', 'P-10', 'T-4', 'T-5', 'F-7', 'M-3', 'M-4',
    'M-5', 'P-15', 'C-1', 'C-2', 'T-12', 'T-13', 'F-4', 'F-5', 'D-14',
    'T-9', 'P-14', 'T-8', 'P-11', 'D-15', 'D-16', 'M-7', 'F-8'
]
SMAP=[  'P-1', 'S-1', 'E-1', 'E-2', 'E-3', 'E-4', 'E-5', 'E-6', 'E-7',
    'E-8', 'E-9', 'E-10', 'E-11', 'E-12', 'E-13', 'A-1', 'D-1', 'P-3',
    'D-2', 'D-3', 'D-4', 'A-2', 'A-3', 'A-4', 'G-1', 'G-2', 'D-5',
    'D-6', 'D-7', 'F-1', 'P-4', 'G-3', 'T-1', 'T-2', 'D-8', 'D-9',
    'F-2', 'G-4', 'T-3', 'D-11', 'B-1', 'G-6', 'G-7', 'P-7',
    'R-1', 'A-5', 'A-6', 'A-7', 'D-13', 'A-8', 'A-9', 'F-3']


MSL=['M-6',
    'M-1', 'M-2', 'S-2', 'P-10', 'T-4', 'T-5', 'F-7', 'M-3', 'M-4',
    'M-5', 'P-15', 'C-1', 'C-2', 'T-12', 'T-13', 'F-4', 'F-5', 'D-14',
    'T-9', 'P-14', 'T-8', 'P-11', 'D-15', 'D-16', 'M-7', 'F-8']

errormsl=[]
for signal_name in MSL:
    data = load_signal(signal_name)
    context = pipeline.fit(data, output_=0)
    context = pipeline.fit(**context, output_=1, start_=1)
    context = pipeline.fit(**context, output_=2, start_=2)
    context = pipeline.fit(**context, output_=3, start_=3)
    context = pipeline.fit(**context, output_=4, start_=4)
    context = pipeline.fit(**context, output_=5, start_=5)
    print(context['errors'])
    errormsl.append(context['errors'])
    


Train on 2691 samples, validate on 673 samples
Epoch 1/5
2691/2691 [==============================] - 22s 8ms/step - loss: 0.0995 - mse: 0.0995 - val_loss: 0.0180 - val_mse: 0.0180
Epoch 2/5
2691/2691 [==============================] - 13s 5ms/step - loss: 0.0110 - mse: 0.0110 - val_loss: 0.0187 - val_mse: 0.0187
Epoch 3/5
2691/2691 [==============================] - 13s 5ms/step - loss: 0.0080 - mse: 0.0080 - val_loss: 0.0191 - val_mse: 0.0191
Epoch 4/5
2691/2691 [==============================] - 13s 5ms/step - loss: 0.0074 - mse: 0.0074 - val_loss: 0.0186 - val_mse: 0.0186
Epoch 5/5
3364/3364 [==============================] - 15s 4ms/step
[0.00702238 0.00702238 0.00702238 ... 0.18257122 0.18257096 0.18257072]
Train on 3388 samples, validate on 848 samples
Epoch 1/5
3388/3388 [==============================] - 25s 7ms/step - loss: 0.0854 - mse: 0.0854 - val_loss: 0.0081 - val_mse: 0.0081
Epoch 2/5
3388/3388 [==============================] - 16s 5ms/step - loss: 0.0492 - mse: 0.0492

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



6984/6984 [==============================] - 44s 6ms/step - loss: 0.0355 - mse: 0.0355 - val_loss: 0.0586 - val_mse: 0.0586
Epoch 2/5
6984/6984 [==============================] - 33s 5ms/step - loss: 0.0074 - mse: 0.0074 - val_loss: 0.0683 - val_mse: 0.0683
Epoch 3/5
6984/6984 [==============================] - 33s 5ms/step - loss: 0.0070 - mse: 0.0070 - val_loss: 0.0542 - val_mse: 0.0542
Epoch 4/5
6984/6984 [==============================] - 34s 5ms/step - loss: 0.0063 - mse: 0.0063 - val_loss: 0.0559 - val_mse: 0.0559
Epoch 5/5
8730/8730 [==============================] - 25s 3ms/step
[0.00945901 0.00945949 0.00941534 ... 0.21306242 0.21274152 0.21271113]
Train on 1613 samples, validate on 404 samples
Epoch 1/5
1613/1613 [==============================] - 18s 11ms/step - loss: 0.1310 - mse: 0.1310 - val_loss: 0.0658 - val_mse: 0.0658
Epoch 2/5
1613/1613 [==============================] - 8s 5ms/step - loss: 0.0649 - mse: 0.0649 - val_loss: 0.0649 - val_mse: 0.0649
Epoch 3/5
1613/1613

In [29]:
ff=[]
from statistics import mean
for i in range(len(errormsl)):
    avg=errormsl[i]
    f=np.average(avg)
    ff.append(f)
mean(ff)   

0.09029078456948221